apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler-depoyment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: news-backend
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 1