apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-scraper
  #namespace: admin-che
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-scraper
  template:
    metadata:
      labels:
        app: feed-scraper
    spec:
      containers:
        - command:
            - java
            - -Dscraper.feeds.url=http://feeds.bbci.co.uk/news/world/rss.xml
            - -Dscraper.feed.backend.host=news-backend
            - -jar
            - /usr/local/lib/feed-scraper.jar
          image: us.gcr.io/nth-agent-362522/feed-scraper    #todo: replace <project_ID> with your actual project_ID 
          name: feed-scraper