apiVersion: v1
kind: Service
metadata:
  labels:
    app: location-extractor
  name: location-extractor
  #namespace: admin-che
spec:
  #type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 80
  selector:
    app: location-extractor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-extractor
  #namespace: admin-che
  labels:
    app: location-extractor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-extractor
  template:
    metadata:
      labels:
        app: location-extractor
    spec:
      containers:
        - image: us.gcr.io/nth-agent-362522/location-extractor   #todo: replace <project_ID> with your actual project_ID 
          name: location-extractor
          imagePullPolicy: Always
          ports:
            - containerPort: 80