apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgis-persistent-volume-claim
  labels:
    app: postgis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard